import React, { useState, useEffect } from 'react';
import { ArchiveInput } from '../ui/ArchiveInput';
import { ArchiveSelect } from '../ui/ArchiveSelect';
import { ArchiveSlider } from '../ui/ArchiveSlider';
import { Icons } from '../ui/Icons';

const ExportContent = ({ characterData, onCopy, onDownload, updateData, subtab = 0 }) => {
  const [exportFormat, setExportFormat] = useState('json');
  const [selectedSections, setSelectedSections] = useState(['all']);
  const [importText, setImportText] = useState('');
  const [importError, setImportError] = useState('');
  const [importSuccess, setImportSuccess] = useState('');

  // Section list
  const allSections = [
    'identity', 'appearance', 'psychology', 'physique', 'voice', 'history',
    'relationships', 'intimacy', 'occupation', 'intelligence', 'worldview',
    'favorites', 'behavior', 'secrets', 'goals', 'directives'
  ];

  // Toggle section selection
  const toggleSection = (section) => {
    if (section === 'all') {
      setSelectedSections(['all']);
    } else {
      setSelectedSections(prev => {
        const filtered = prev.filter(s => s !== 'all');
        if (filtered.includes(section)) {
          return filtered.filter(s => s !== section);
        } else {
          return [...filtered, section];
        }
      });
    }
  };

  // Get filtered data
  const getFilteredData = () => {
    if (selectedSections.includes('all')) return characterData;
    const filtered = {};
    selectedSections.forEach(s => {
      if (characterData[s]) filtered[s] = characterData[s];
    });
    return filtered;
  };

  // Generate text export
  const generateTextExport = () => {
    const data = getFilteredData();
    let text = `CHARACTER PROFILE: ${characterData.identity?.core?.firstName || 'Unnamed'} ${characterData.identity?.core?.lastName || ''}\n`;
    text += `${'='.repeat(60)}\n\n`;

    const addSection = (title, obj) => {
      if (!obj) return;
      text += `${title.toUpperCase()}\n${'-'.repeat(40)}\n`;
      Object.entries(obj).forEach(([key, val]) => {
        if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
          text += `\n[${key}]\n`;
          Object.entries(val).forEach(([k, v]) => {
            if (Array.isArray(v) && v.length > 0) text += `  ${k}: ${v.join(', ')}\n`;
            else if (v && v !== '' && v !== 5) text += `  ${k}: ${v}\n`;
          });
        }
      });
      text += '\n';
    };

    Object.entries(data).forEach(([key, val]) => {
      addSection(key, val);
    });

    text += `\nGenerated by Persona Loom v7\n`;
    text += `Export Date: ${new Date().toISOString()}\n`;
    return text;
  };

  // Generate Markdown export
  const generateMarkdownExport = () => {
    const data = getFilteredData();
    const name = `${characterData.identity?.core?.firstName || 'Unnamed'} ${characterData.identity?.core?.lastName || ''}`;
    let md = `# ${name}\n\n`;
    md += `> Generated by Persona Loom v7 on ${new Date().toLocaleDateString()}\n\n`;

    const addSection = (title, obj, level = 2) => {
      if (!obj) return;
      md += `${'#'.repeat(level)} ${title}\n\n`;
      Object.entries(obj).forEach(([key, val]) => {
        if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
          md += `${'#'.repeat(level + 1)} ${key.charAt(0).toUpperCase() + key.slice(1)}\n\n`;
          Object.entries(val).forEach(([k, v]) => {
            if (Array.isArray(v) && v.length > 0) {
              md += `- **${k}**: ${v.join(', ')}\n`;
            } else if (v && v !== '' && v !== 5) {
              md += `- **${k}**: ${v}\n`;
            }
          });
          md += '\n';
        }
      });
    };

    Object.entries(data).forEach(([key, val]) => {
      addSection(key.charAt(0).toUpperCase() + key.slice(1), val);
    });

    return md;
  };

  // Generate ElevenLabs voice description
  const generateElevenLabsVoice = () => {
    const voice = characterData.voice || {};
    const design = voice.design || {};
    const languages = voice.languages || {};

    const parts = [];
    if (design.voiceGender) parts.push(design.voiceGender);
    if (design.voiceAge) parts.push(`${design.voiceAge} voice`);

    const pitch = design.pitch || 5;
    if (pitch <= 3) parts.push('deep');
    else if (pitch >= 7) parts.push('high-pitched');

    const warmth = design.timbreWarmth || 5;
    if (warmth >= 7) parts.push('warm');
    else if (warmth <= 3) parts.push('cold');

    const smoothness = design.timbreSmoothness || 5;
    if (smoothness >= 7) parts.push('smooth');
    else if (smoothness <= 3) parts.push('rough');

    if (design.breathiness >= 6) parts.push('breathy');
    if (design.roughness >= 6) parts.push('raspy');
    if (design.voiceTexture) parts.push(design.voiceTexture.toLowerCase());
    if (design.emotionalTone) parts.push(`${design.emotionalTone.toLowerCase()} tone`);

    if (languages.accent) {
      const strength = languages.accentStrength || 5;
      const strengthWord = strength <= 3 ? 'slight' : strength >= 7 ? 'strong' : 'moderate';
      parts.push(`with ${strengthWord} ${languages.accent} accent`);
    }

    return parts.join(', ') || 'No voice settings configured.';
  };

  // Generate RP summary (for Character.AI, etc)
  const generateRPSummary = () => {
    const identity = characterData.identity || {};
    const core = identity.core || {};
    const vitals = identity.vitals || {};
    const psychology = characterData.psychology || {};
    const appearance = characterData.appearance || {};
    const directives = characterData.directives || {};

    let summary = `Name: ${core.firstName || 'Unknown'} ${core.lastName || ''}\n`;
    if (core.nickname) summary += `Nickname: "${core.nickname}"\n`;
    summary += `Age: ${vitals.age || 'Unknown'}\n`;
    summary += `Gender: ${vitals.genderIdentity || 'Unknown'}\n`;
    if (vitals.nationality) summary += `Nationality: ${vitals.nationality}\n`;
    summary += '\n';

    if (psychology.core?.personalityTraits?.length > 0) {
      summary += `Personality: ${psychology.core.personalityTraits.join(', ')}\n`;
    }
    if (psychology.core?.mbtiType) {
      summary += `MBTI: ${psychology.core.mbtiType}\n`;
    }
    summary += '\n';

    if (appearance.body?.height || appearance.body?.build) {
      summary += `Build: ${appearance.body?.height || ''} ${appearance.body?.build || ''}\n`;
    }
    if (appearance.hair?.color) {
      summary += `Hair: ${appearance.hair.color} ${appearance.hair.style || ''}\n`;
    }
    if (appearance.eyes?.color) {
      summary += `Eyes: ${appearance.eyes.color}\n`;
    }
    summary += '\n';

    // Add directive outputs if available
    if (directives.formatting?.responseLength) {
      summary += `[Response Style Preferences]\n`;
    }

    return summary;
  };

  // Generate Directive text
  const generateDirectiveOutput = () => {
    const directives = characterData.directives || {};
    let output = '';

    // Directive Responses
    output += '=== DIRECTIVE RESPONSES (250 chars) ===\n';
    const directiveParts = [];
    Object.entries(directives.formatting || {}).forEach(([k, v]) => {
      if (v) directiveParts.push(`${k}: ${v}`);
    });
    Object.entries(directives.writingStyle || {}).forEach(([k, v]) => {
      if (v) directiveParts.push(`${k}: ${v}`);
    });
    output += directiveParts.join('. ') || 'Not configured';
    output += '\n\n';

    // Ruler
    output += '=== RULER (750 chars) ===\n';
    const ruler = directives.ruler || {};
    const rulerParts = [];
    Object.entries(ruler).forEach(([k, v]) => {
      if (v && k !== 'importantRules' && k !== 'customRules') {
        rulerParts.push(`${k}: ${v}`);
      }
    });
    if (ruler.importantRules?.length > 0) {
      rulerParts.push(`Important rules: ${ruler.importantRules.join(', ')}`);
    }
    output += rulerParts.join('\n') || 'Not configured';
    output += '\n\n';

    // Proactive
    output += '=== PROACTIVE (300 chars) ===\n';
    const proactive = directives.proactive || {};
    const proactiveParts = [];
    Object.entries(proactive).forEach(([k, v]) => {
      if (v && k !== 'actionTypes' && k !== 'customDirective') {
        proactiveParts.push(`${k}: ${v}`);
      }
    });
    if (proactive.actionTypes?.length > 0) {
      proactiveParts.push(`Actions: ${proactive.actionTypes.join(', ')}`);
    }
    output += proactiveParts.join('\n') || 'Not configured';

    return output;
  };

  // Handle export
  const handleExport = (format) => {
    let content, filename, type;

    switch (format) {
      case 'json':
        content = JSON.stringify(getFilteredData(), null, 2);
        filename = `${characterData.identity?.core?.firstName || 'character'}_full.json`;
        type = 'application/json';
        break;
      case 'txt':
        content = generateTextExport();
        filename = `${characterData.identity?.core?.firstName || 'character'}_profile.txt`;
        type = 'text/plain';
        break;
      case 'md':
        content = generateMarkdownExport();
        filename = `${characterData.identity?.core?.firstName || 'character'}_profile.md`;
        type = 'text/markdown';
        break;
      case 'elevenlabs':
        content = generateElevenLabsVoice();
        filename = `${characterData.identity?.core?.firstName || 'character'}_voice.txt`;
        type = 'text/plain';
        break;
      case 'rp':
        content = generateRPSummary();
        filename = `${characterData.identity?.core?.firstName || 'character'}_rp.txt`;
        type = 'text/plain';
        break;
      case 'directives':
        content = generateDirectiveOutput();
        filename = `${characterData.identity?.core?.firstName || 'character'}_directives.txt`;
        type = 'text/plain';
        break;
      default:
        content = JSON.stringify(getFilteredData(), null, 2);
        filename = 'character.json';
        type = 'application/json';
    }

    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Handle import
  const handleImport = () => {
    setImportError('');
    setImportSuccess('');

    try {
      const data = JSON.parse(importText);

      // Validate basic structure
      if (typeof data !== 'object') {
        throw new Error('Invalid data format');
      }

      // Merge with existing data
      if (updateData) {
        Object.entries(data).forEach(([key, value]) => {
          if (allSections.includes(key)) {
            updateData(key, value);
          }
        });
        setImportSuccess('Character data imported successfully!');
        setImportText('');
      }
    } catch (e) {
      setImportError(`Import failed: ${e.message}`);
    }
  };

  // Handle file upload
  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        setImportText(event.target.result);
      };
      reader.readAsText(file);
    }
  };

  // Subtab content
  const subtabContent = {
    // SUBTAB 0: Quick Export
    0: (
      <div className="space-y-6">
        <div className="bg-gradient-to-br from-slate-800 to-slate-900 rounded-sm p-4 text-white">
          <h3 className="font-mono text-sm font-bold mb-2">⚡ QUICK EXPORT</h3>
          <p className="font-mono text-xs text-slate-300">Export your character in various formats.</p>
        </div>

        {/* Export format selection */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-4">📁 Export Format</h4>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {[
              { id: 'json', icon: '📄', label: 'JSON', desc: 'Full data, machine-readable' },
              { id: 'txt', icon: '📝', label: 'Text', desc: 'Human-readable summary' },
              { id: 'md', icon: '📋', label: 'Markdown', desc: 'Formatted documentation' },
            ].map(format => (
              <button
                key={format.id}
                onClick={() => setExportFormat(format.id)}
                className={`p-4 border-2 rounded-sm transition-all text-left ${
                  exportFormat === format.id ? 'border-blue-500 bg-blue-50' : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <div className="text-2xl mb-2">{format.icon}</div>
                <div className="font-mono text-sm font-bold">{format.label}</div>
                <div className="font-mono text-[10px] text-gray-500">{format.desc}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Quick actions */}
        <div className="flex gap-3">
          <button
            onClick={() => handleExport(exportFormat)}
            className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-gray-900 text-white font-mono text-xs uppercase hover:bg-gray-700 rounded-sm"
          >
            <Icons.Download width={16} height={16} />
            Download {exportFormat.toUpperCase()}
          </button>
          <button
            onClick={onCopy}
            className="flex items-center gap-2 px-4 py-3 border-2 border-gray-900 font-mono text-xs uppercase hover:bg-gray-100 rounded-sm"
          >
            <Icons.Copy width={16} height={16} />
            Copy JSON
          </button>
        </div>

        {/* Preview */}
        <div className="bg-gray-50 border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-xs font-bold text-gray-600 mb-3">👁️ Preview</h4>
          <div className="bg-white border border-gray-200 rounded-sm p-4 max-h-[300px] overflow-auto">
            <pre className="font-mono text-[10px] text-gray-600 whitespace-pre-wrap">
              {exportFormat === 'json'
                ? JSON.stringify(characterData, null, 2).substring(0, 2000) + '...'
                : exportFormat === 'md'
                  ? generateMarkdownExport().substring(0, 2000) + '...'
                  : generateTextExport().substring(0, 2000) + '...'
              }
            </pre>
          </div>
        </div>
      </div>
    ),

    // SUBTAB 1: Platform Templates
    1: (
      <div className="space-y-6">
        <div className="bg-gradient-to-br from-purple-800 to-pink-800 rounded-sm p-4 text-white">
          <h3 className="font-mono text-sm font-bold mb-2">🎯 PLATFORM TEMPLATES</h3>
          <p className="font-mono text-xs text-purple-200">Export optimized for specific RP platforms and TTS services.</p>
        </div>

        {/* TTS Platforms */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-4">🎙️ Text-to-Speech Platforms</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* ElevenLabs */}
            <div className="border border-purple-200 rounded-sm p-4 bg-purple-50/30">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-2xl">🎙️</span>
                <div>
                  <h5 className="font-mono text-sm font-bold text-purple-800">ElevenLabs</h5>
                  <p className="font-mono text-[10px] text-gray-500">Voice Design description</p>
                </div>
              </div>
              <div className="bg-white p-3 rounded border border-purple-200 mb-3 max-h-20 overflow-auto">
                <p className="font-mono text-[10px] text-gray-700">{generateElevenLabsVoice()}</p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => {navigator.clipboard.writeText(generateElevenLabsVoice()); alert('ElevenLabs voice description copied!');}}
                  className="flex-1 px-3 py-2 bg-purple-600 hover:bg-purple-700 text-white font-mono text-xs rounded-sm"
                >
                  Copy
                </button>
              </div>
            </div>

            {/* Generic TTS */}
            <div className="border border-blue-200 rounded-sm p-4 bg-blue-50/30">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-2xl">🔊</span>
                <div>
                  <h5 className="font-mono text-sm font-bold text-blue-800">Generic TTS</h5>
                  <p className="font-mono text-[10px] text-gray-500">For other TTS services</p>
                </div>
              </div>
              <div className="bg-white p-3 rounded border border-blue-200 mb-3 max-h-20 overflow-auto">
                <p className="font-mono text-[10px] text-gray-700">
                  {`Voice: ${characterData.voice?.design?.voiceGender || 'Not set'}, ${characterData.voice?.design?.voiceAge || ''}\nPitch: ${characterData.voice?.design?.pitch || 5}/10\nSpeed: ${characterData.voice?.design?.speed || 5}/10\nAccent: ${characterData.voice?.languages?.accent || 'None'}`}
                </p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => {
                    const text = `Voice: ${characterData.voice?.design?.voiceGender || 'Not set'}, ${characterData.voice?.design?.voiceAge || ''}\nPitch: ${characterData.voice?.design?.pitch || 5}/10\nSpeed: ${characterData.voice?.design?.speed || 5}/10\nAccent: ${characterData.voice?.languages?.accent || 'None'}`;
                    navigator.clipboard.writeText(text);
                    alert('Generic TTS settings copied!');
                  }}
                  className="flex-1 px-3 py-2 bg-blue-600 hover:bg-blue-700 text-white font-mono text-xs rounded-sm"
                >
                  Copy
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* RP Platforms */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-4">🎭 RP Platforms</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Kindroid */}
            <div className="border border-pink-200 rounded-sm p-4 bg-pink-50/30">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-2xl">🤖</span>
                <div>
                  <h5 className="font-mono text-sm font-bold text-pink-800">Kindroid</h5>
                  <p className="font-mono text-[10px] text-gray-500">Backstory + Directive + Ruler</p>
                </div>
              </div>
              <div className="bg-white p-3 rounded border border-pink-200 mb-3 max-h-20 overflow-auto">
                <pre className="font-mono text-[10px] text-gray-700 whitespace-pre-wrap">{`[Backstory]\n${characterData.history?.childhood?.childhoodSummary || 'No backstory set'}\n\n[Directive]\n${generateDirectiveOutput().substring(0, 150)}...`}</pre>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => {
                    const kindroid = `[Backstory]\n${characterData.history?.childhood?.childhoodSummary || ''}\n${characterData.history?.formative?.formativeEvent || ''}\n\n[Directive Responses]\n${generateDirectiveOutput()}\n\n[Proactive Mode]\nSee Directives tab for proactive settings.`;
                    navigator.clipboard.writeText(kindroid);
                    alert('Kindroid format copied!');
                  }}
                  className="flex-1 px-3 py-2 bg-pink-600 hover:bg-pink-700 text-white font-mono text-xs rounded-sm"
                >
                  Copy Full
                </button>
              </div>
            </div>

            {/* Character.AI */}
            <div className="border border-amber-200 rounded-sm p-4 bg-amber-50/30">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-2xl">💬</span>
                <div>
                  <h5 className="font-mono text-sm font-bold text-amber-800">Character.AI</h5>
                  <p className="font-mono text-[10px] text-gray-500">Character definition format</p>
                </div>
              </div>
              <div className="bg-white p-3 rounded border border-amber-200 mb-3 max-h-20 overflow-auto">
                <pre className="font-mono text-[10px] text-gray-700 whitespace-pre-wrap">{generateRPSummary().substring(0, 200)}...</pre>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => {navigator.clipboard.writeText(generateRPSummary()); alert('Character.AI format copied!');}}
                  className="flex-1 px-3 py-2 bg-amber-600 hover:bg-amber-700 text-white font-mono text-xs rounded-sm"
                >
                  Copy
                </button>
              </div>
            </div>

            {/* SillyTavern */}
            <div className="border border-green-200 rounded-sm p-4 bg-green-50/30">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-2xl">🍺</span>
                <div>
                  <h5 className="font-mono text-sm font-bold text-green-800">SillyTavern</h5>
                  <p className="font-mono text-[10px] text-gray-500">Character card format (W++)</p>
                </div>
              </div>
              <div className="bg-white p-3 rounded border border-green-200 mb-3 max-h-20 overflow-auto">
                <pre className="font-mono text-[10px] text-gray-700 whitespace-pre-wrap">{`[character("${characterData.identity?.core?.firstName || 'Name'}")]\n{\nAge("${characterData.identity?.vitals?.age || '?'}")\nGender("${characterData.identity?.vitals?.genderIdentity || '?'}")\nPersonality("${characterData.psychology?.core?.personalityTraits?.slice(0,3).join('" + "') || '?'}")\n}`}</pre>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => {
                    const wpp = `[character("${characterData.identity?.core?.firstName || 'Name'}")]\n{\nAge("${characterData.identity?.vitals?.age || '?'}")\nGender("${characterData.identity?.vitals?.genderIdentity || '?'}")\nPersonality("${characterData.psychology?.core?.personalityTraits?.join('" + "') || '?'}")\nAppearance("${characterData.appearance?.hair?.color || ''} hair" + "${characterData.appearance?.eyes?.color || ''} eyes")\nOccupation("${characterData.occupation?.jobs?.[0]?.title || '?'}")\n}`;
                    navigator.clipboard.writeText(wpp);
                    alert('SillyTavern W++ format copied!');
                  }}
                  className="flex-1 px-3 py-2 bg-green-600 hover:bg-green-700 text-white font-mono text-xs rounded-sm"
                >
                  Copy W++
                </button>
              </div>
            </div>

            {/* Janitor AI */}
            <div className="border border-indigo-200 rounded-sm p-4 bg-indigo-50/30">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-2xl">🧹</span>
                <div>
                  <h5 className="font-mono text-sm font-bold text-indigo-800">Janitor AI</h5>
                  <p className="font-mono text-[10px] text-gray-500">Character bio format</p>
                </div>
              </div>
              <div className="bg-white p-3 rounded border border-indigo-200 mb-3 max-h-20 overflow-auto">
                <pre className="font-mono text-[10px] text-gray-700 whitespace-pre-wrap">{`Name: ${characterData.identity?.core?.firstName || ''} ${characterData.identity?.core?.lastName || ''}\nAge: ${characterData.identity?.vitals?.age || '?'}\nGender: ${characterData.identity?.vitals?.genderIdentity || '?'}`}</pre>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => {
                    const janitor = `Name: ${characterData.identity?.core?.firstName || ''} ${characterData.identity?.core?.lastName || ''}\nNickname: ${characterData.identity?.core?.nickname || ''}\nAge: ${characterData.identity?.vitals?.age || '?'}\nGender: ${characterData.identity?.vitals?.genderIdentity || '?'}\nNationality: ${characterData.identity?.vitals?.nationality || '?'}\n\nAppearance:\n- Hair: ${characterData.appearance?.hair?.color || '?'} ${characterData.appearance?.hair?.style || ''}\n- Eyes: ${characterData.appearance?.eyes?.color || '?'}\n- Height: ${characterData.appearance?.body?.height || '?'}\n- Build: ${characterData.appearance?.body?.build || '?'}\n\nPersonality: ${characterData.psychology?.core?.personalityTraits?.join(', ') || '?'}\nMBTI: ${characterData.psychology?.core?.mbtiType || '?'}\n\nOccupation: ${characterData.occupation?.jobs?.[0]?.title || '?'}`;
                    navigator.clipboard.writeText(janitor);
                    alert('Janitor AI format copied!');
                  }}
                  className="flex-1 px-3 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-mono text-xs rounded-sm"
                >
                  Copy
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Documentation Formats */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-4">📄 Documentation Formats</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Markdown */}
            <div className="border border-gray-200 rounded-sm p-4">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-2xl">📋</span>
                <div>
                  <h5 className="font-mono text-sm font-bold text-gray-800">Markdown</h5>
                  <p className="font-mono text-[10px] text-gray-500">Full documentation</p>
                </div>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => {navigator.clipboard.writeText(generateMarkdownExport()); alert('Markdown copied!');}}
                  className="flex-1 px-3 py-2 bg-gray-600 hover:bg-gray-700 text-white font-mono text-xs rounded-sm"
                >
                  Copy MD
                </button>
                <button
                  onClick={() => handleExport('md')}
                  className="flex-1 px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 font-mono text-xs rounded-sm"
                >
                  Download
                </button>
              </div>
            </div>

            {/* Directives */}
            <div className="border border-gray-200 rounded-sm p-4">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-2xl">⚙️</span>
                <div>
                  <h5 className="font-mono text-sm font-bold text-gray-800">Directives Only</h5>
                  <p className="font-mono text-[10px] text-gray-500">All RP settings</p>
                </div>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => {navigator.clipboard.writeText(generateDirectiveOutput()); alert('Directives copied!');}}
                  className="flex-1 px-3 py-2 bg-gray-600 hover:bg-gray-700 text-white font-mono text-xs rounded-sm"
                >
                  Copy
                </button>
                <button
                  onClick={() => handleExport('directives')}
                  className="flex-1 px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 font-mono text-xs rounded-sm"
                >
                  Download
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Tips */}
        <div className="bg-blue-50 border border-blue-200 rounded-sm p-4">
          <h4 className="font-mono text-xs font-bold text-blue-800 mb-2">💡 Platform Tips</h4>
          <ul className="font-mono text-[10px] text-blue-700 space-y-1">
            <li>• <strong>Kindroid:</strong> Use Directive Responses (250 chars), Ruler (750 chars), Proactive (300 chars)</li>
            <li>• <strong>Character.AI:</strong> Keep definitions concise, focus on personality and speaking style</li>
            <li>• <strong>SillyTavern:</strong> W++ format works best, include scenario for context</li>
            <li>• <strong>ElevenLabs:</strong> Voice Design accepts natural language descriptions</li>
          </ul>
        </div>
      </div>
    ),

    // SUBTAB 2: Custom Export
    2: (
      <div className="space-y-6">
        <div className="bg-gradient-to-br from-teal-800 to-cyan-800 rounded-sm p-4 text-white">
          <h3 className="font-mono text-sm font-bold mb-2">🔧 CUSTOM EXPORT</h3>
          <p className="font-mono text-xs text-teal-200">Select specific sections to export.</p>
        </div>

        {/* Section selection */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-4">📁 Select Sections</h4>
          <div className="flex flex-wrap gap-2 mb-4">
            <button
              onClick={() => toggleSection('all')}
              className={`px-3 py-1 rounded-sm font-mono text-xs transition-all ${
                selectedSections.includes('all') ? 'bg-blue-600 text-white' : 'bg-gray-100 hover:bg-gray-200'
              }`}
            >
              All Sections
            </button>
            {allSections.map(section => (
              <button
                key={section}
                onClick={() => toggleSection(section)}
                className={`px-3 py-1 rounded-sm font-mono text-xs transition-all capitalize ${
                  selectedSections.includes(section) ? 'bg-blue-600 text-white' : 'bg-gray-100 hover:bg-gray-200'
                }`}
              >
                {section}
              </button>
            ))}
          </div>
          <p className="font-mono text-[10px] text-gray-500">
            Selected: {selectedSections.includes('all') ? 'All sections' : selectedSections.join(', ') || 'None'}
          </p>
        </div>

        {/* Export buttons */}
        <div className="grid grid-cols-3 gap-3">
          <button
            onClick={() => handleExport('json')}
            className="p-4 border border-gray-200 rounded-sm hover:bg-gray-50 text-center"
          >
            <div className="text-2xl mb-2">📄</div>
            <div className="font-mono text-xs font-bold">JSON</div>
          </button>
          <button
            onClick={() => handleExport('txt')}
            className="p-4 border border-gray-200 rounded-sm hover:bg-gray-50 text-center"
          >
            <div className="text-2xl mb-2">📝</div>
            <div className="font-mono text-xs font-bold">Text</div>
          </button>
          <button
            onClick={() => handleExport('md')}
            className="p-4 border border-gray-200 rounded-sm hover:bg-gray-50 text-center"
          >
            <div className="text-2xl mb-2">📋</div>
            <div className="font-mono text-xs font-bold">Markdown</div>
          </button>
        </div>

        {/* Preview filtered data */}
        <div className="bg-gray-50 border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-xs font-bold text-gray-600 mb-3">👁️ Preview (filtered)</h4>
          <div className="bg-white border border-gray-200 rounded-sm p-4 max-h-[300px] overflow-auto">
            <pre className="font-mono text-[10px] text-gray-600 whitespace-pre-wrap">
              {JSON.stringify(getFilteredData(), null, 2).substring(0, 3000)}...
            </pre>
          </div>
        </div>
      </div>
    ),

    // SUBTAB 3: Import/Backup
    3: (
      <div className="space-y-6">
        <div className="bg-gradient-to-br from-amber-800 to-orange-800 rounded-sm p-4 text-white">
          <h3 className="font-mono text-sm font-bold mb-2">📥 IMPORT / BACKUP</h3>
          <p className="font-mono text-xs text-amber-200">Import character data or create backups.</p>
        </div>

        {/* Backup current */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-3">💾 Create Backup</h4>
          <p className="font-mono text-xs text-gray-500 mb-4">Download a full backup of your character.</p>
          <button
            onClick={() => {
              const backup = {
                _meta: {
                  version: 'PersonaLoom v6',
                  exportDate: new Date().toISOString(),
                  characterName: characterData.identity?.core?.firstName || 'Unknown'
                },
                data: characterData
              };
              const blob = new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = `${characterData.identity?.core?.firstName || 'character'}_backup_${new Date().toISOString().split('T')[0]}.json`;
              a.click();
              URL.revokeObjectURL(url);
            }}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-green-600 hover:bg-green-700 text-white font-mono text-xs uppercase rounded-sm"
          >
            <Icons.Download width={16} height={16} />
            Download Full Backup
          </button>
        </div>

        {/* Import */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-3">📤 Import Character</h4>
          <p className="font-mono text-xs text-gray-500 mb-4">Load character data from a JSON file or paste JSON text.</p>

          {/* File upload */}
          <div className="mb-4">
            <label className="block font-mono text-xs text-gray-600 mb-2">Upload File</label>
            <input
              type="file"
              accept=".json"
              onChange={handleFileUpload}
              className="w-full px-3 py-2 border border-gray-200 rounded-sm font-mono text-xs"
            />
          </div>

          {/* Paste JSON */}
          <div className="mb-4">
            <label className="block font-mono text-xs text-gray-600 mb-2">Or Paste JSON</label>
            <textarea
              value={importText}
              onChange={(e) => setImportText(e.target.value)}
              placeholder='{"identity": {...}, "appearance": {...}}'
              className="w-full h-32 px-3 py-2 border border-gray-200 rounded-sm font-mono text-xs resize-none"
            />
          </div>

          {/* Error/Success messages */}
          {importError && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-sm">
              <p className="font-mono text-xs text-red-700">{importError}</p>
            </div>
          )}
          {importSuccess && (
            <div className="mb-4 p-3 bg-green-50 border border-green-200 rounded-sm">
              <p className="font-mono text-xs text-green-700">{importSuccess}</p>
            </div>
          )}

          <button
            onClick={handleImport}
            disabled={!importText}
            className={`w-full flex items-center justify-center gap-2 px-4 py-3 font-mono text-xs uppercase rounded-sm ${
              importText
                ? 'bg-blue-600 hover:bg-blue-700 text-white'
                : 'bg-gray-200 text-gray-400 cursor-not-allowed'
            }`}
          >
            <Icons.Upload width={16} height={16} />
            Import Data
          </button>
        </div>

        {/* Warning */}
        <div className="bg-amber-50 border border-amber-200 rounded-sm p-4">
          <h4 className="font-mono text-xs font-bold text-amber-800 mb-2">⚠️ Warning</h4>
          <p className="font-mono text-[10px] text-amber-700">
            Importing data will merge with existing data. Make a backup first if you want to preserve current data.
          </p>
        </div>
      </div>
    ),

    // SUBTAB 4: Character Card (Visual)
    4: (
      <div className="space-y-6">
        <div className="bg-gradient-to-br from-rose-800 to-pink-800 rounded-sm p-4 text-white">
          <h3 className="font-mono text-sm font-bold mb-2">🎴 CHARACTER CARD</h3>
          <p className="font-mono text-xs text-rose-200">Generate a visual character card for sharing.</p>
        </div>

        {/* Character Card Preview */}
        <div className="flex justify-center">
          <div
            id="character-card"
            className="w-[400px] bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 rounded-lg overflow-hidden shadow-2xl border border-slate-700"
          >
            {/* Header */}
            <div className="relative h-32 bg-gradient-to-r from-purple-600 via-blue-600 to-cyan-600">
              <div className="absolute inset-0 bg-black/20" />
              <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-slate-900 to-transparent" />
            </div>

            {/* Avatar */}
            <div className="relative -mt-12 flex justify-center">
              <div className="w-24 h-24 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 border-4 border-slate-900 flex items-center justify-center text-4xl font-bold text-white shadow-lg">
                {characterData.identity?.core?.firstName?.charAt(0)?.toUpperCase() || '?'}
              </div>
            </div>

            {/* Info */}
            <div className="p-6 text-center">
              <h2 className="text-2xl font-bold text-white mb-1">
                {characterData.identity?.core?.firstName || 'Unnamed'} {characterData.identity?.core?.lastName || ''}
              </h2>
              {characterData.identity?.core?.nicknames && (
                <p className="text-slate-400 text-sm mb-3">"{characterData.identity.core.nicknames}"</p>
              )}

              {/* Tags */}
              <div className="flex flex-wrap justify-center gap-2 mb-4">
                {characterData.identity?.vitals?.age && (
                  <span className="px-2 py-1 bg-blue-500/20 text-blue-300 rounded text-xs">{characterData.identity.vitals.age} years</span>
                )}
                {characterData.identity?.vitals?.genderIdentity && (
                  <span className="px-2 py-1 bg-pink-500/20 text-pink-300 rounded text-xs">{characterData.identity.vitals.genderIdentity}</span>
                )}
                {characterData.psychology?.framework?.mbtiType && (
                  <span className="px-2 py-1 bg-purple-500/20 text-purple-300 rounded text-xs">{characterData.psychology.framework.mbtiType}</span>
                )}
              </div>

              {/* Quick Stats */}
              <div className="grid grid-cols-3 gap-2 mb-4">
                {characterData.appearance?.hair?.naturalColor && (
                  <div className="p-2 bg-slate-800 rounded">
                    <div className="text-[10px] text-slate-500">Hair</div>
                    <div className="text-xs text-slate-300">{characterData.appearance.hair.currentColor || characterData.appearance.hair.naturalColor}</div>
                  </div>
                )}
                {characterData.appearance?.face?.eyeColor && (
                  <div className="p-2 bg-slate-800 rounded">
                    <div className="text-[10px] text-slate-500">Eyes</div>
                    <div className="text-xs text-slate-300">{characterData.appearance.face.eyeColor}</div>
                  </div>
                )}
                {characterData.appearance?.body?.height && (
                  <div className="p-2 bg-slate-800 rounded">
                    <div className="text-[10px] text-slate-500">Height</div>
                    <div className="text-xs text-slate-300">{characterData.appearance.body.height}</div>
                  </div>
                )}
              </div>

              {/* Traits */}
              {characterData.psychology?.traits?.positiveTraits?.length > 0 && (
                <div className="flex flex-wrap justify-center gap-1 mb-4">
                  {characterData.psychology.traits.positiveTraits.slice(0, 5).map((trait, i) => (
                    <span key={i} className="px-2 py-0.5 bg-slate-700 text-slate-300 rounded-full text-[10px]">{trait}</span>
                  ))}
                </div>
              )}

              {/* Occupation */}
              {characterData.occupation?.jobs?.[0]?.title && (
                <div className="text-sm text-slate-400">
                  💼 {characterData.occupation.jobs[0].title}
                  {characterData.occupation.jobs[0].company && ` @ ${characterData.occupation.jobs[0].company}`}
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="px-6 py-3 bg-slate-800/50 border-t border-slate-700 flex justify-between items-center">
              <span className="font-mono text-[10px] text-slate-500">Persona Loom v7</span>
              <span className="font-mono text-[10px] text-slate-500">{new Date().toLocaleDateString()}</span>
            </div>
          </div>
        </div>

        {/* Export Card Options */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-4">📥 Export Card</h4>
          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={() => {
                const card = document.getElementById('character-card');
                if (card) {
                  alert('Card HTML copied! For best results, use a screenshot tool or browser extension to capture the card.');
                  navigator.clipboard.writeText(card.outerHTML);
                }
              }}
              className="p-3 border border-gray-200 rounded-sm hover:bg-gray-50 text-center"
            >
              <div className="text-xl mb-1">📋</div>
              <div className="font-mono text-xs font-bold">Copy HTML</div>
            </button>
            <button
              onClick={() => {
                alert('💡 Tip: Use your browser\'s screenshot feature or a tool like Lightshot to capture the card above!');
              }}
              className="p-3 border border-gray-200 rounded-sm hover:bg-gray-50 text-center"
            >
              <div className="text-xl mb-1">📸</div>
              <div className="font-mono text-xs font-bold">Screenshot</div>
            </button>
          </div>
        </div>

        {/* Card Style Options */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-3">🎨 Card Includes</h4>
          <div className="grid grid-cols-2 gap-2">
            {[
              { label: 'Name & Nickname', included: !!characterData.identity?.core?.firstName },
              { label: 'Age & Gender', included: !!characterData.identity?.vitals?.age },
              { label: 'MBTI Type', included: !!characterData.psychology?.framework?.mbtiType },
              { label: 'Appearance', included: !!(characterData.appearance?.hair?.naturalColor || characterData.appearance?.face?.eyeColor) },
              { label: 'Personality Traits', included: (characterData.psychology?.traits?.positiveTraits?.length || 0) > 0 },
              { label: 'Occupation', included: !!characterData.occupation?.jobs?.[0]?.title },
            ].map((item, i) => (
              <div key={i} className={`flex items-center gap-2 p-2 rounded ${item.included ? 'bg-green-50' : 'bg-gray-50'}`}>
                <span className={item.included ? 'text-green-600' : 'text-gray-400'}>{item.included ? '✓' : '✗'}</span>
                <span className="font-mono text-xs text-gray-700">{item.label}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    ),

    // SUBTAB 5: Share
    5: (
      <div className="space-y-6">
        <div className="bg-gradient-to-br from-cyan-800 to-blue-800 rounded-sm p-4 text-white">
          <h3 className="font-mono text-sm font-bold mb-2">🔗 SHARE CHARACTER</h3>
          <p className="font-mono text-xs text-cyan-200">Share your character with others.</p>
        </div>

        {/* Share Link Generator */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-3">🌐 Share via Link</h4>
          <p className="font-mono text-xs text-gray-500 mb-4">Generate a shareable link containing your character data.</p>

          <div className="space-y-3">
            <button
              onClick={() => {
                const compressed = btoa(encodeURIComponent(JSON.stringify(characterData)));
                const shareUrl = `${window.location.origin}${window.location.pathname}#import=${compressed.substring(0, 100)}...`;
                navigator.clipboard.writeText(compressed);
                alert('Character data encoded and copied!\n\nNote: Full sharing links require a backend service. The encoded data has been copied to your clipboard for manual sharing.');
              }}
              className="w-full px-4 py-3 bg-cyan-600 hover:bg-cyan-700 text-white font-mono text-xs uppercase rounded-sm"
            >
              📋 Copy Encoded Data
            </button>

            <div className="p-3 bg-gray-50 rounded-sm">
              <div className="font-mono text-[10px] text-gray-500 mb-1">Encoded character data (first 100 chars):</div>
              <div className="font-mono text-[10px] text-gray-700 break-all">
                {btoa(encodeURIComponent(JSON.stringify(characterData))).substring(0, 100)}...
              </div>
            </div>
          </div>
        </div>

        {/* Quick Share Text */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-3">📝 Quick Share Text</h4>
          <p className="font-mono text-xs text-gray-500 mb-4">Copy a text summary to share on social media or forums.</p>

          <div className="bg-gray-50 p-4 rounded-sm mb-3">
            <pre className="font-mono text-xs text-gray-700 whitespace-pre-wrap">
{`✨ Meet ${characterData.identity?.core?.firstName || 'my character'} ${characterData.identity?.core?.lastName || ''}!

${characterData.identity?.vitals?.age ? `📅 Age: ${characterData.identity.vitals.age}` : ''}
${characterData.identity?.vitals?.genderIdentity ? `⚧ Gender: ${characterData.identity.vitals.genderIdentity}` : ''}
${characterData.psychology?.framework?.mbtiType ? `🧠 MBTI: ${characterData.psychology.framework.mbtiType}` : ''}
${characterData.psychology?.traits?.positiveTraits?.length > 0 ? `💫 Traits: ${characterData.psychology.traits.positiveTraits.slice(0, 3).join(', ')}` : ''}
${characterData.occupation?.jobs?.[0]?.title ? `💼 ${characterData.occupation.jobs[0].title}` : ''}

Created with Persona Loom v7 🎭`}
            </pre>
          </div>

          <button
            onClick={() => {
              const text = `✨ Meet ${characterData.identity?.core?.firstName || 'my character'} ${characterData.identity?.core?.lastName || ''}!\n\n${characterData.identity?.vitals?.age ? `📅 Age: ${characterData.identity.vitals.age}\n` : ''}${characterData.identity?.vitals?.genderIdentity ? `⚧ Gender: ${characterData.identity.vitals.genderIdentity}\n` : ''}${characterData.psychology?.framework?.mbtiType ? `🧠 MBTI: ${characterData.psychology.framework.mbtiType}\n` : ''}${characterData.psychology?.traits?.positiveTraits?.length > 0 ? `💫 Traits: ${characterData.psychology.traits.positiveTraits.slice(0, 3).join(', ')}\n` : ''}${characterData.occupation?.jobs?.[0]?.title ? `💼 ${characterData.occupation.jobs[0].title}\n` : ''}\nCreated with Persona Loom v7 🎭`;
              navigator.clipboard.writeText(text);
              alert('Share text copied to clipboard!');
            }}
            className="w-full px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 font-mono text-xs rounded-sm"
          >
            Copy Share Text
          </button>
        </div>

        {/* Platform-Specific Sharing */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-3">📲 Platform Sharing</h4>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              { name: 'Twitter/X', icon: '𝕏', color: 'bg-black' },
              { name: 'Discord', icon: '💬', color: 'bg-indigo-600' },
              { name: 'Reddit', icon: '🔴', color: 'bg-orange-600' },
              { name: 'Tumblr', icon: '📝', color: 'bg-blue-900' },
            ].map((platform, i) => (
              <button
                key={i}
                onClick={() => {
                  const text = `Check out my character ${characterData.identity?.core?.firstName || ''} created with Persona Loom!`;
                  navigator.clipboard.writeText(text);
                  alert(`Text for ${platform.name} copied!\n\nPaste it along with your character card or JSON file.`);
                }}
                className={`p-3 ${platform.color} text-white rounded-sm hover:opacity-90 transition-opacity`}
              >
                <div className="text-xl mb-1">{platform.icon}</div>
                <div className="font-mono text-[10px]">{platform.name}</div>
              </button>
            ))}
          </div>
        </div>

        {/* QR Code (placeholder) */}
        <div className="bg-white border border-gray-200 rounded-sm p-4">
          <h4 className="font-mono text-sm font-bold text-gray-800 mb-3">📱 QR Code</h4>
          <div className="flex justify-center">
            <div className="w-32 h-32 bg-gray-100 border-2 border-dashed border-gray-300 rounded flex items-center justify-center">
              <span className="font-mono text-xs text-gray-400 text-center">QR Code<br/>(requires backend)</span>
            </div>
          </div>
          <p className="font-mono text-[10px] text-gray-500 text-center mt-2">
            QR code generation requires a server-side service.
          </p>
        </div>

        {/* Export for specific platforms */}
        <div className="bg-blue-50 border border-blue-200 rounded-sm p-4">
          <h4 className="font-mono text-xs font-bold text-blue-800 mb-2">💡 Sharing Tips</h4>
          <ul className="font-mono text-[10px] text-blue-700 space-y-1">
            <li>• For RP platforms: Use Platform Templates to get formatted exports</li>
            <li>• For visual sharing: Use Character Card and screenshot</li>
            <li>• For backup/transfer: Use Import/Backup for full JSON</li>
            <li>• Encoded data can be decoded using Base64 decoders</li>
          </ul>
        </div>
      </div>
    ),
  };

  return (
    <div className="animate-fadeIn">
      <div className="mb-8">
        <span className="inline-block bg-[#2C3E50] text-white font-mono text-[9px] px-2 py-1 tracking-[0.15em]">SYSTEM // EXPORT</span>
      </div>
      <h1 className="font-serif text-4xl font-black italic text-gray-900 mb-4">Export & Import</h1>
      <p className="font-mono text-xs text-gray-500 mb-8">Export your character in multiple formats or import existing data.</p>

      {subtabContent[subtab] || subtabContent[0]}
    </div>
  );
};
// ============================================================================
// MAIN APP
// ============================================================================

export default ExportContent;
